#! perl

# Based on:
# https://github.com/shyiko/urxvt-clipboard-paste-on-right-click
# https://git.devuan.org/bert/urxvt-pasta
# @version 0.0.1
# @license MIT

=head1 NAME

right-click-paste - paste the contents of the clipboard with the right click.

=head1 DESCRIPTION

To install:
- copy right-click-paste to ~/.urxvt/ext/
- add "URxvt.perl-ext-common: ...,selection-to-clipboard,confirm-paste,right-click-paste" to ~/.Xresources

URxvt also supports ctrl+right+click

=cut

sub on_button_press {
  my ($self, $event) = @_;
  $self->ModLevel3Mask;
  if ($event->{button} == 3) {
     $self->selection_clear;
     $self->selection_request (urxvt::CurrentTime, 3);
     return 1;
  }
  return;
}

sub on_button_release {
  my ($self, $event) = @_;
  $self->ModLevel3Mask;
  if ($event->{button} == 3) {
    $self->selection_clear;
    return 1;
  }
  return;
}
